version: '3'
services:
    web:
        image: nginx:alpine
        container_name: test_js_case_nginx
        volumes:
            - "./web:/var/www/html"
            - "./hosts:/etc/nginx/conf.d"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=localhost
        restart: always
        depends_on:
            - php
        networks:
            - internal
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        container_name: test_js_case_php
        volumes:
            - "./web:/var/www/html"
            - "./php:/usr/local/etc/php/custom.d"
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
            PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
        networks:
            - internal 
networks:
        internal:
            driver: bridge
            ipam:
                driver: default
                config:
                    - subnet: 192.168.220.0/28            
